# fly.toml app configuration file generated for task1-morning-resonance-3986 on 2024-07-02T03:21:28-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "task1-morning-resonance-3986"
primary_region = "lhr"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.processes]]
    command = "gunicorn -w 4 -b 0.0.0.0:8080 main:app"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1